### ISSUE TITLE
The example doesn't work in iPhone

### ISSUE THREAD

**Issue by Andex09** [microsoftgraph/msgraph-training-xamarin#31] opened 2021-12-13 17:18 UTC
I followed the explanation steps, but it doesn't work on an iPhone, it never returns after var interactiveAuthResult = await interactiveRequest.ExecuteAsync ();

**Comment by jasonjoh** [comment] 2022-01-04 18:33
@Andex09 my apologies for the slow response. I've been on vacation over the holidays. To clarify, are you trying this on an actual iPhone, or in the emulator? Also, are you using the dependency versions specified in the tutorial, or the latest versions?

```
Install-Package Microsoft.Identity.Client -Version 4.35.1 -Project GraphTutorial
Install-Package Microsoft.Identity.Client -Version 4.35.1 -Project GraphTutorial.Android
Install-Package Microsoft.Identity.Client -Version 4.35.1 -Project GraphTutorial.iOS
Install-Package Microsoft.Graph -Version 4.1.0 -Project GraphTutorial
```

**Comment by Andex09** [comment] 2022-01-04 19:33
I am trying this on an iPhone SE conected a Windows pc, I am using the dependency versions specified in the tutorial. I am reading for this problem and I found this https://developercommunity.visualstudio.com/t/xamarin-ios-in-visual-studio-2022-problem-with-com/1590471 My problem is a Native Crash

**Comment by jasonjoh** [comment] 2022-01-04 20:13
Ah ok interesting. I'm going to leave this open but for now it doesn't seem actionable. I'm going to be refreshing this sample shortly so it will be interesting to see if I can reproduce it.

**Comment by jasonjoh** [comment] 2023-01-13 21:13
Looks like they have fixed the issue according to https://developercommunity.visualstudio.com/t/Unable-to-use-MSAL-with-locally-connecte/1573064. Closing this here.

**Closed by jasonjoh** 2023-01-13 21:13 UTC
Labels: not actionable
